// Fill out your copyright notice in the Description page of Project Settings.


#include "ItemInfoUi.h"

#include "ContentBrowserItemData.h"
#include "HttpModule.h"
#include "IImageWrapperModule.h"
#include "JsonObjectConverter.h"
#include "Blueprint/WidgetTree.h"
#include "Components/Button.h"
#include "Components/HorizontalBox.h"
#include "Components/Image.h"
#include "Components/ScrollBox.h"
#include "Components/SizeBox.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Interfaces/IHttpResponse.h"
#include "Project/ApiObject/Npc/ApiItemObject.h"

class IImageWrapper;
class FHttpModule;
class USizeBox;
class UVerticalBox;
class UHorizontalBox;
class UImage;

void UItemInfoUi::NativeConstruct()
{
	Super::NativeConstruct();
}

void UItemInfoUi::LoadItems()
{
    UE_LOG(LogTemp, Display, TEXT("Loading items"));

    UApiItemObject* Api = NewObject<UApiItemObject>();
    Api->OnItemInfoResponse.BindLambda([this](FString String)
    {
        FItemRows ItemRows;
        if (!FJsonObjectConverter::JsonObjectStringToUStruct(String, &ItemRows))
        { UE_LOG(LogTemp, Warning, TEXT("‚ùå Failed to parse ItemRows")); return; }

        VScroll->ClearChildren();
        ButtonItemMap.Empty();

        for (const FItemRow& Item : ItemRows.response)
        {
            // Î≤ÑÌäº + Ìïú Ï§Ñ(Row)
            UButton* ClickButton = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());
            UHorizontalBox* RowBox = WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass());

            // üî∏ Î≤ÑÌäº Ìà¨Î™Ö Ï≤òÎ¶¨
            FButtonStyle TransparentStyle;
            TransparentStyle.SetNormal(FSlateNoResource());
            TransparentStyle.SetHovered(FSlateNoResource());
            TransparentStyle.SetPressed(FSlateNoResource());
            TransparentStyle.Normal.TintColor = FSlateColor(FLinearColor(0, 0, 0, 0));
            TransparentStyle.Hovered.TintColor = FSlateColor(FLinearColor(0, 0, 0, 0.1f));
            TransparentStyle.Pressed.TintColor = FSlateColor(FLinearColor(0, 0, 0, 0.2f));
            ClickButton->SetStyle(TransparentStyle);

              // üîπ UImage ÏúÑÏ†Ø Î®ºÏ†Ä ÏÉùÏÑ± (placeholder)
            UImage* Icon = WidgetTree->ConstructWidget<UImage>(UImage::StaticClass());
            UTexture2D* DummyTex = UTexture2D::CreateTransient(64, 64);
            Icon->SetBrushFromTexture(DummyTex);
            Icon->SetColorAndOpacity(FLinearColor::Gray);

            USizeBox* IconBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass());
            IconBox->SetWidthOverride(80.f);
            IconBox->SetHeightOverride(80.f);
            IconBox->AddChild(Icon);
            RowBox->AddChildToHorizontalBox(IconBox);

            // üî∏ 2Ï∞® ÏöîÏ≤≠: image_url ‚Üí Ïù¥ÎØ∏ÏßÄ Îã§Ïö¥Î°úÎìú
            FHttpModule* Http = &FHttpModule::Get();
            TSharedRef<IHttpRequest, ESPMode::ThreadSafe> ImgRequest = Http->CreateRequest();
            FString Str = Item.image_url.Replace(TEXT("\\"), TEXT("/"));
            ImgRequest->SetURL(FString::Printf(TEXT("http://127.0.0.1:8000/%s"), *Str));
            ImgRequest->SetVerb("GET");

            // ÎÇ¥Î∂Ä BindLambda (Ï§ëÏ≤© ÏΩúÎ∞±)
            ImgRequest->OnProcessRequestComplete().BindLambda([Icon](FHttpRequestPtr ImgReq, FHttpResponsePtr ImgRes, bool bOk)
            {
                if (!bOk || !ImgRes.IsValid())
                {
                    UE_LOG(LogTemp, Error, TEXT("Ïù¥ÎØ∏ÏßÄ Îã§Ïö¥Î°úÎìú Ïã§Ìå®"));
                    return;
                }

                const TArray<uint8>& Data = ImgRes->GetContent();

                IImageWrapperModule& ImageWrapperModule = FModuleManager::LoadModuleChecked<IImageWrapperModule>(FName("ImageWrapper"));
                TSharedPtr<IImageWrapper> Wrapper = ImageWrapperModule.CreateImageWrapper(EImageFormat::PNG);

                if (Wrapper.IsValid() && Wrapper->SetCompressed(Data.GetData(), Data.Num()))
                {
                    TArray64<uint8> RawData;
                    if (Wrapper->GetRaw(ERGBFormat::BGRA, 8, RawData))
                    {
                        UTexture2D* Texture = UTexture2D::CreateTransient(
                            Wrapper->GetWidth(),
                            Wrapper->GetHeight(),
                            PF_B8G8R8A8
                        );
                 
                        void* TextureData = Texture->GetPlatformData()->Mips[0].BulkData.Lock(LOCK_READ_WRITE);
                        FMemory::Memcpy(TextureData, RawData.GetData(), RawData.Num());
                        Texture->GetPlatformData()->Mips[0].BulkData.Unlock();
                        Texture->UpdateResource();
                 
                        AsyncTask(ENamedThreads::GameThread, [Icon, Texture]()
                        {
                            Icon->SetBrushFromTexture(Texture);
                            Icon->SetColorAndOpacity(FLinearColor::White);
                            UE_LOG(LogTemp, Warning, TEXT("‚úÖ ÏïÑÏù¥ÌÖú Ïù¥ÎØ∏ÏßÄ Î°úÎìú ÏôÑÎ£å"));
                        });
                    }
                }
            });

            ImgRequest->ProcessRequest();

            // üî∏ ÌÖçÏä§Ìä∏ ÏÖÄ ÏÉùÏÑ± Ìï®Ïàò
            auto MakeTextCell = [&](const FString& Value, float Width, FLinearColor Color = FLinearColor::White)
            {
                USizeBox* CellBox = WidgetTree->ConstructWidget<USizeBox>(USizeBox::StaticClass());
                CellBox->SetWidthOverride(Width);

                UTextBlock* Text = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
                Text->SetText(FText::FromString(Value));
                Text->SetColorAndOpacity(FSlateColor(Color));
                Text->SetJustification(ETextJustify::Left);
                Text->SetAutoWrapText(false);
                Text->SetMargin(FMargin(5.f, 0.f, 5.f, 0.f));
                // Ìè∞Ìä∏ ÌÅ¨Í∏∞ ÏßÄÏ†ï (ÌïúÍ∏Ä Íπ®Ïßê Î∞©ÏßÄÎ•º ÏúÑÌï¥ ÏßÄÏ†ïÌïòÏßÄ ÏïäÏïÑÎèÑ Îê®)
                // Text->SetFont(FSlateFontInfo(FPaths::EngineContentDir() / TEXT("Slate/Fonts/Roboto-Regular.ttf"), 20));
                CellBox->AddChild(Text);

                return CellBox;
            };

            // üî∏ Îì±Í∏â ÏÉâÏÉÅ
            FLinearColor RarityColor = FLinearColor::White;
            if (Item.Rarity.Contains(TEXT("Ï†ÑÏÑ§")))      RarityColor = FLinearColor(1.f, 0.85f, 0.2f);
            else if (Item.Rarity.Contains(TEXT("Ìù¨Í∑Ä"))) RarityColor = FLinearColor(0.3f, 0.6f, 1.f);
            else if (Item.Rarity.Contains(TEXT("ÏùºÎ∞ò"))) RarityColor = FLinearColor(0.85f, 0.85f, 0.85f);

            // üî∏ ÏóëÏÖÄ Ïä§ÌÉÄÏùº Ïª¨Îüº Íµ¨ÏÑ±
            RowBox->AddChildToHorizontalBox(MakeTextCell(Item.Name, 300.f));
            RowBox->AddChildToHorizontalBox(MakeTextCell(Item.Rarity, 120.f, RarityColor));
            RowBox->AddChildToHorizontalBox(MakeTextCell(Item.Type, 100.f, FLinearColor(0.7f, 1.f, 0.7f)));

            // Î≤ÑÌäºÏóê RowBox Ï∂îÍ∞Ä
            ClickButton->AddChild(RowBox);
            VScroll->AddChild(ClickButton);

            // Î≤ÑÌäºÎ≥Ñ ÏïÑÏù¥ÌÖú Îç∞Ïù¥ÌÑ∞ Ï†ÄÏû•
            ButtonItemMap.Add(ClickButton, Item);

            // ÌÅ¥Î¶≠ Ïù¥Î≤§Ìä∏ Î∞îÏù∏Îî©
            ClickButton->OnClicked.AddDynamic(this, &UItemInfoUi::OnItemClick);
        }
    });

    Api->ItemInfoResponse();
}

void UItemInfoUi::OnItemClick()
{
    // ÌÅ¥Î¶≠Îêú Î≤ÑÌäº ÌÉêÏÉâ
    for (auto& Pair : ButtonItemMap)
    {
        UButton* Button = Pair.Key;
        if (Button->HasKeyboardFocus()) // ÌòÑÏû¨ Ìè¨Ïª§Ïä§ Î∞õÏùÄ Î≤ÑÌäº
        {
            const FItemRow& Item = Pair.Value;

            if (DetailPanel)
            {
                DetailPanel->ClearChildren();

                // Ï†úÎ™©
                UTextBlock* Title = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
                Title->SetText(FText::FromString(Item.Name));
                Title->SetColorAndOpacity(FSlateColor(FLinearColor::White));

                // Î≥∏Î¨∏ ÏÑ§Î™Ö
                UTextBlock* Desc = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
                Desc->SetText(FText::FromString(Item.Description));
                Desc->SetAutoWrapText(true);
                Desc->SetMargin(FMargin(10.f));

                DetailPanel->AddChild(Title);
                DetailPanel->AddChild(Desc);
            }
            break;
        }
    }
}

